# TTS 训练参数

gpu: 0
lr: 2e-4
batch_size: 4
epochs: 100
ckpt_path: "F:\\models_tts_fs+mg\\demo"

train_data: "G:\\Yuanshen\\4.jiaba_cut_16K_cersion-2.0_label-100pieces.txt"
valid_data: "G:\\Yuanshen\\4.jiaba_cut_16K_cersion-2.0_label-100pieces.txt"
test_data: "G:\\Yuanshen\\4.jiaba_cut_16K_cersion-2.0_label-100pieces.txt"

spk_map: "G:\\Yuanshen\\spk_map.txt"
phoneme_map: "G:\\Yuanshen\\phoneme_map.txt"

mfa_dir: "G:\\Yuanshen\\3.loudnorm_16K_version-2.0-mfa_output"

max_ckpt_save: 5  # 最多同时存储这么多 ckpt 文件

log_every_steps: 10  # 每多少个step展示一次日志

# 数据集的操作
sample_rate: 16000  # 采样率，默认 16K Hz，如果输入数据不是这个采样率，就会重采样；
hop_size: 200  # 每多少个点计算一次FFT；需要能被 sample_rate 整除；
fft_size: 2048
win_length: 800  # for 16K Hz
window: "hann"
num_mels: 80  # numbers of mels

mel_f_min: 0  # Mel谱的频率的最小值
mel_f_max: 8000  # Mel谱的频率的最大值

shuffle: True
input_max_seconds: 12  # 输入音频的最大长度/秒，默认是 12秒
input_max_tokens: 196  # 输入音素的最大长度/个，默认是 256个字符

phonemes_size: 213  # 音素的数量
speaker_size: 64  # 音色的数量