# VGG base 模型的所有参数；

gpu: 0
lr: 1e-3
batch_size: 64
epochs: 1000
ckpt_path: "F:\\models_images\\demo"

train_data: "G:\\Images\\3.labeled_json_0921.train.txt"
valid_data: "G:\\Images\\3.labeled_json_0921.valid.txt"
shuffle: True
n_classes: 160
input_shape: [224, 224]

max_ckpt_save: 5  # 最多同时存储这么多 ckpt 文件

